"""
Dry run utilities for the xespresso GUI.

This module provides functionality to generate input files for Quantum ESPRESSO
calculations without actually submitting them, useful for testing and debugging.
"""

import os
import streamlit as st
from pathlib import Path

try:
    from ase import io as ase_io
    from xespresso import Espresso
    from xespresso.xio import write_espresso_in
    ASE_AVAILABLE = True
except ImportError:
    ASE_AVAILABLE = False


def generate_input_files(atoms, calc_params, workdir, structure_filename="structure.cif"):
    """
    Generate Quantum ESPRESSO input files for a calculation.
    
    This uses xespresso's built-in file generation capabilities to create
    the necessary input files without running the calculation.
    
    Args:
        atoms: ASE Atoms object with the structure
        calc_params: Dictionary of calculation parameters for Espresso calculator
        workdir: Working directory where files will be created
        structure_filename: Name for the structure file (default: structure.cif)
    
    Returns:
        Dictionary with paths to created files, or None if failed
    """
    if not ASE_AVAILABLE:
        st.error("ASE and xespresso not available for input file generation")
        return None
    
    try:
        # Create working directory
        os.makedirs(workdir, exist_ok=True)
        
        # Save structure file
        structure_path = os.path.join(workdir, structure_filename)
        ase_io.write(structure_path, atoms)
        
        # Create Espresso calculator with the parameters
        calc = Espresso(**calc_params)
        
        # Set the calculator for the atoms
        atoms.calc = calc
        
        # Set the directory for the calculation
        calc.directory = workdir
        calc.prefix = 'espresso'
        
        # Write input file using xespresso's write_input method
        # This generates the input file without running the calculation
        calc.write_input(atoms)
        
        # Determine input file path
        input_file = os.path.join(workdir, f"{calc.prefix}.pwi")
        
        # Return paths to generated files
        return {
            'structure': structure_path,
            'input': input_file,
            'workdir': workdir,
            'prefix': calc.prefix
        }
        
    except Exception as e:
        st.error(f"Error generating input files: {e}")
        import traceback
        st.code(traceback.format_exc())
        return None


def preview_input_file(filepath):
    """
    Display preview of a generated input file.
    
    Args:
        filepath: Path to the input file
    """
    try:
        with open(filepath, 'r') as f:
            content = f.read()
        
        st.subheader("Input File Preview")
        st.code(content, language='fortran')
        
        # Show file size and line count
        lines = content.split('\n')
        st.caption(f"File: {filepath} | {len(lines)} lines | {len(content)} bytes")
        
    except Exception as e:
        st.error(f"Error reading input file: {e}")


def create_job_script(workdir, machine_config, code_path, input_file, nprocs=1):
    """
    Create a job submission script for the calculation.
    
    Args:
        workdir: Working directory
        machine_config: Machine configuration dict or Machine object
        code_path: Path to the QE executable
        input_file: Name of the input file
        nprocs: Number of processors
    
    Returns:
        Path to the created job script
    """
    try:
        script_path = os.path.join(workdir, 'run.sh')
        
        # Get machine details
        if hasattr(machine_config, 'scheduler'):
            scheduler = machine_config.scheduler
            launcher = machine_config.launcher
        else:
            scheduler = machine_config.get('scheduler', 'direct')
            launcher = machine_config.get('launcher', 'mpirun -np {nprocs}')
        
        # Format launcher command
        launcher_cmd = launcher.format(nprocs=nprocs)
        
        # Create script content
        script_lines = [
            "#!/bin/bash",
            f"# Generated by xespresso GUI",
            "",
        ]
        
        # Add scheduler directives if needed
        if scheduler == 'slurm':
            script_lines.extend([
                f"#SBATCH --ntasks={nprocs}",
                "#SBATCH --time=24:00:00",
                "",
            ])
        elif scheduler == 'pbs':
            script_lines.extend([
                f"#PBS -l nodes=1:ppn={nprocs}",
                "#PBS -l walltime=24:00:00",
                "",
            ])
        
        # Add execution command
        script_lines.extend([
            f"cd {workdir}",
            f"{launcher_cmd} {code_path} -in {input_file} > espresso.out",
            "",
        ])
        
        # Write script
        with open(script_path, 'w') as f:
            f.write('\n'.join(script_lines))
        
        # Make executable
        os.chmod(script_path, 0o755)
        
        return script_path
        
    except Exception as e:
        st.error(f"Error creating job script: {e}")
        return None
