#!/bin/bash
#SBATCH --job-name=test
#SBATCH --output=test.out
#SBATCH --error=test.err
#SBATCH --wait
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --partition=parallel
#SBATCH --time=01:00:00

# Configurações do xespressorc

export OMP_NUM_THREADS=1

module purge
module load quantum_espresso


# Comando de execução
srun --mpi=pmi2 pw.x  -in  test.pwi  >  test.pwo
