"""Job Submission Page for xespresso GUI."""
import streamlit as st
import os
from pathlib import Path

def render_job_submission_page():
    """Render the job submission page with job file viewer."""
    st.header("Job Submission & Job File Viewer")
    st.markdown("""
    This page allows you to:
    - View generated job submission files
    - Review job scripts before submission
    """)
    
    # Job File Viewer Section
    st.subheader("📄 Job File Viewer")
    st.markdown("""
    Browse and view job submission files that have been generated by calculations.
    Job files are typically named `job_file` and contain the submission script for schedulers like SLURM.
    """)
    
    # Directory selection
    col1, col2 = st.columns([3, 1])
    with col1:
        job_dir = st.text_input(
            "Calculation Directory:",
            value=os.getcwd(),
            help="Enter the path to the calculation directory containing job files"
        )
    with col2:
        browse_button = st.button("📂 Browse Current")
        if browse_button:
            job_dir = os.getcwd()
    
    if job_dir and os.path.isdir(job_dir):
        # List job files in the directory
        job_files = []
        for root, dirs, files in os.walk(job_dir):
            for file in files:
                if file == "job_file" or file.endswith(".sh") or file.endswith(".slurm"):
                    job_files.append(os.path.join(root, file))
        
        if job_files:
            st.success(f"Found {len(job_files)} job file(s)")
            
            # Select a job file to view
            selected_job_file = st.selectbox(
                "Select Job File to View:",
                job_files,
                format_func=lambda x: os.path.relpath(x, job_dir)
            )
            
            if selected_job_file:
                try:
                    with open(selected_job_file, 'r') as f:
                        job_content = f.read()
                    
                    # Show file info
                    file_stat = os.stat(selected_job_file)
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("File Size", f"{file_stat.st_size} bytes")
                    with col2:
                        st.metric("Lines", len(job_content.splitlines()))
                    with col3:
                        from datetime import datetime
                        mod_time = datetime.fromtimestamp(file_stat.st_mtime)
                        st.metric("Modified", mod_time.strftime("%Y-%m-%d %H:%M"))
                    
                    # Display job file content
                    st.subheader("Job File Content")
                    st.code(job_content, language="bash", line_numbers=True)
                    
                    # Download button
                    st.download_button(
                        label="⬇️ Download Job File",
                        data=job_content,
                        file_name=os.path.basename(selected_job_file),
                        mime="text/plain"
                    )
                    
                    # Parse and display key information
                    st.subheader("Job File Summary")
                    
                    # Extract SLURM directives if present
                    slurm_directives = []
                    commands = []
                    for line in job_content.splitlines():
                        line = line.strip()
                        if line.startswith("#SBATCH"):
                            slurm_directives.append(line)
                        elif line and not line.startswith("#"):
                            commands.append(line)
                    
                    if slurm_directives:
                        st.markdown("**SLURM Directives:**")
                        for directive in slurm_directives:
                            st.markdown(f"- `{directive}`")
                    
                    if commands:
                        st.markdown("**Commands:**")
                        for cmd in commands[:10]:  # Show first 10 commands
                            st.markdown(f"- `{cmd}`")
                        if len(commands) > 10:
                            st.markdown(f"... and {len(commands) - 10} more commands")
                    
                except Exception as e:
                    st.error(f"Error reading job file: {e}")
        else:
            st.warning(f"⚠️ No job files found in '{job_dir}' or its subdirectories.")
            st.info("""
            **Tip:** Job files are typically named:
            - `job_file` (default)
            - `*.sh` (shell scripts)
            - `*.slurm` (SLURM scripts)
            
            Make sure you've generated calculation files first in the Calculation Setup page.
            """)
    elif job_dir:
        st.error(f"❌ Directory not found: {job_dir}")
    
    # Additional features section
    st.markdown("---")
    st.subheader("🔧 Additional Features")
    st.info("""
    **Coming Soon:**
    - Direct job submission from GUI
    - Job status monitoring
    - Job history and logs viewer
    - Job script templates
    """)
