#!/bin/bash
#SBATCH --job-name=scf
#SBATCH --output=scf.out
#SBATCH --error=scf.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=00:30:00
#SBATCH --partition=parallel

# Configurações do xespressorc

export OMP_NUM_THREADS=1

module purge
module load quantum-espresso/7.4.1-intel-mkl-mpi


# Comando de execução
srun --mpi=pmi2 pw.x  -in  scf.pwi  >  scf.pwo
